#!/usr/bin/env ruby

require 'TerraformDevKit'

TDK = TerraformDevKit

if ARGV.length != 2
  puts 'USAGE: wait_for_url <url> <retries>'
  exit
end

url = ARGV[0]
retries = ARGV[1].to_i

TDK.with_retry(retries) do
  TDK::Request.new(url).execute(raise_on_codes: ['500'])
end
